version: "3.8"
services:
  server:
    image: 'nginx:1.21.6-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./:/code/financial-simulator
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  php:
    build:
      context: ./
      dockerfile: docker/php.Dockerfile
    volumes:
      - ./:/code/financial-simulator
    entrypoint: [ "php" ]
    depends_on:
      - postgres
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php.Dockerfile
    ports:
      - '9001:9000'
    volumes:
      - ./:/code/financial-simulator
    depends_on:
      - postgres
  phpunit:
    build:
      context: ./
      dockerfile: docker/php.Dockerfile
    entrypoint: [ "vendor/bin/phpunit" ]
    volumes:
      - ./:/code/financial-simulator
    depends_on:
      - sqlite
  composer:
    build:
      context: ./
      dockerfile: docker/php.Dockerfile
    entrypoint: [ "composer" ]
    volumes:
      - ./:/code/financial-simulator
      - ./docker/volumes/composer:/tmp
  postgres:
    image: 'postgres:14.3-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: simulator
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
  sqlite:
    image: 'keinos/sqlite3:3.38.5'
  npm:
    build:
      context: ./
      dockerfile: docker/node.Dockerfile
    volumes:
      - ./:/code/financial-simulator
