version: "3.8"
services:
  server:
    image: 'nginx:1.21.6-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/dev/php-fpm.Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
  php:
    build:
      context: ./
      dockerfile: docker/dev/php.Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
  phpunit:
    build:
      context: ./
      dockerfile: docker/dev/php.Dockerfile
    entrypoint: [ "vendor/bin/phpunit" ]
    volumes:
      - ./:/var/www/html
    depends_on:
      - sqlite
  composer:
    build:
      context: ./
      dockerfile: docker/dev/php.Dockerfile
    entrypoint: ["composer"]
    volumes:
      - ./:/var/www/html
      - ./docker/dev/volumes/composer:/tmp
  postgres:
    image: 'postgres:14.3-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: simulator
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - ./docker/dev/volumes/postgres:/var/lib/postgresql/data
  sqlite:
    image: 'keinos/sqlite3:3.38.5'
